### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by brandonros** [dwyl/decache#12]
Would you lean away from using this in production servers to reload modules?

**Comment by nelsonic** [comment]
@brandonros I don't see an issue with using this in *production* to delete the cached module so it can be *re*-required.

**Comment by brandonros** [comment]
How about re-requiring lots of modules on production servers?

**Comment by nelsonic** [comment]
@brandonros it depends on the context. 
are you re-requiring modules during the request/processing lifecycle?
requiring modules is `synchronous` so it blocks the event loop, so you should *ideally* not do it while people are waiting for a response.
Which `node_module` are you requiring? a custom package or one from NPM?

**Comment by nelsonic** [comment]
@brandonros guessing you found an answer?
if you still need advice on this, please re-open the issue.
