### ISSUE TITLE
License GPL > MIT ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/decache#14]
A user on StackOverflow mentioned that the GPL licence is an issue:
http://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate/31505483?noredirect=1#comment59432658_31505483

There are a *surprising* number of people using the package on NPM: 
https://www.npmjs.com/package/decache 1.7k p/m

I don't expect anyone will *complain* if I remove the GPL License...

I'm not *precious* about the code so don't mind removing/changing the license...

@besarthoxhaj as the other main contributor to this project do you have any objection to removing the licence or changing it to MIT?

**Comment by besarthoxhaj** [comment]
Hi @nelsonic happy to go for MIT!
