### ISSUE TITLE
call decache with directory names

### ISSUE THREAD

**Issue by stixx200** [dwyl/decache#18]
hi,

it would be nice to include the functionality to decache local modules which are required by directory name.
Example code:
```
// require the decache module:
var decache = require('decache');

// require a module that you wrote"
// --> code located in ./myModule/index.js
var mymod = require('./myModule');

// use your module the way you need to:
console.log(mymod.count()); // 0   (the initial state for our counter is zero)
console.log(mymod.incrementRunCount()); // 1

// delete the cached module:
decache('./myModule');

//
mymod = require('./myModule'); // assuming fresh start
console.log(mymod.count()); // !!!! 1   (decache didn't work)
```

**Comment by nelsonic** [comment]
@stixx200 yes, this would be a useful addition. 
do you have time to send us a Pull Request adding the feature?

**Comment by stixx200** [comment]
@nelsonic thanks for quick response.
not really. i hotfixed it locally for me. but i think this doesn't work for others.

**Comment by nelsonic** [comment]
@stixx200 is your "*hot-fix*" code available on GitHub or as a Gist?
or can you paste it in here? I can work on a PR later today and release a new version if I have a *use-case* to test against.
thanks. 👍

**Comment by stixx200** [comment]
@nelsonic no, it isn't. i just commented out line 58 of decache.js:
`moduleName = require.find(moduleName);`

that worked for me. you can test it with the code of my first post.
Hope this helps!

**Comment by nelsonic** [comment]
@stixx200 that's enough for us to *investigate*... 👍

**Comment by nelsonic** [comment]
@stixx200 this should be fixed in the latest version, would you mind confirming? (_thanks_!)

**Comment by stixx200** [comment]
@nelsonic thank you! this works!

**Comment by nelsonic** [comment]
Sweet! thanks for confirming @stixx200  and thanks to @jupiter for fixing! 🎉
