### ISSUE TITLE
don't remove native c++ node modules from cache

### ISSUE THREAD

**Issue by stixx200** [dwyl/decache#19]
Because nodejs doesn't have the possibility to unload native c++ modules, it's bad to remove them from node cache.
If we want to require a .node file a second time, node throws the error "Module did not self register".

it would be nice to skip these modules like this:

```
searchCache(moduleName, function (mod) {
    if ('.node' !== path.extname(mod.id)) {
        delete require.cache[mod.id];
    } else {
        console.log('skip decache module: ' + mod.id);
    }
});
```

**Comment by nelsonic** [comment]
@stixx200 can you give an *example* of where you are seeing this?
it might be that we just need to add this info to the *readme* warning people not to use it for *native* modules...?

**Comment by stixx200** [comment]
```
// require the decache module:
var decache = require('decache');

var MODULE_NAME_TO_TEST = "bcrypt";

// require native node module
var mymod = require(MODULE_NAME_TO_TEST);

// delete the cached module:
decache(MODULE_NAME_TO_TEST);

mymod = require(MODULE_NAME_TO_TEST); // require native node module a second time
console.log("everything works fine!");
```

code like this doesn't work. You'll get the error "Module did not self register".
The readme warning would be useful, but if you don't know, if your _normal_ module requires a native node module, you'll get this error as well. (like me)
In consequence, you can't decache any modules which have dependencies to native modules.

Node itself checks in the require mechanism if we require a native module with this check:
`if ('.node' !== path.extname(mod.id))`

**Comment by nelsonic** [comment]
@stixx200 do you have time to write a Pull Request to add this check or update the readme? (_thanks_!)

**Comment by nelsonic** [comment]
Thanks to @ryanwholey, `decache@4.4.0` now includes this.
