### ISSUE TITLE
[Discussion] Problem with detection logic

### ISSUE THREAD

**Issue by perrin4869** [dwyl/decache#21]
I setup a sample repo demonstrating the issue: [decache_poc](https://github.com/perrin4869/decache_poc)

Basically, if you have the following directory structure:

```
test/module.js
test/index.js
module.js
```

And you run `decache("./module.js")` on inside `test/index.js` with both `module.js` and `test/module.js` loaded, it will be `module.js` getting decached. As far as I can tell, there is absolutely no way for `decache` to determine which one was meant for removal. Unless someone can come up with a solution to this, I think we have to return to `decache(path.join(__dirname, 'module.js'))`, or at the very least put up a big warning in `README.md` about this issue... Since I don't think this is a terribly unlikely edge case.

**Comment by jupiter** [comment]
Using https://www.npmjs.com/package/caller-callsite may be better than using find.

**Comment by nelsonic** [comment]
@perrin4869 yes, I don't think we _considered_ the use-case of having files with identical names (but different paths) in the _same_ project ... but you're right, this would only find the first one...
using [`caller-callsite`](https://www.npmjs.com/package/caller-callsite) would help us know the *caller* (_which file invoked `decache`_), but we still need to `find` the file that has to be "un-required"... 
the `decache(path.join(__dirname, 'module.js'))` _might_ be the best way of _specifying_ which one of the files you want to "un-require" ...

**Comment by perrin4869** [comment]
@nelsonic The thing is that `path.join(__dirname, 'module.js')` is the only predictable way, as far as I can tell, of specifying which file to un-require. I just keep picturing a developer wasting hours trying to figure out why decache isn't working, even though he expected the correct file to be uncached...
Doing it the current way is just not predictable...

**Comment by nelsonic** [comment]
@perrin4869 please try the latest version of `decache` (v4) with the scenario you are describing and let us know. 👍

**Comment by perrin4869** [comment]
Well, you can really call this nitpicking at this point, but I can come up with a different scenario where the new approach fails. If you first load `decache` from a different, but I can come up with a different directory, as I do [here](https://github.com/perrin4869/decache_poc/blob/master/test/index.js) in `setup.js`, then the wrong file gets decached again... sorry couldn't help it ><;;

**Comment by perrin4869** [comment]
I mean it's true it's deliberately making the script fail... but that's the whole point right?

**Comment by nelsonic** [comment]
@perrin4869 I think it might be worth adding a "non-usage" section to the readme... ("_don't use decache this way..._")

**Comment by perrin4869** [comment]
Well, I can't think of any such case so as far as I'm concerned we can close this issue :)

**Comment by nelsonic** [comment]
Thanks! closing. 👍
