### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by brandonros** [dwyl/decache#22]
Say I am invalidating a 'index.js', and that 'index.js' requires another 10 files. Will those 10 be invalidated as well?

**Comment by nelsonic** [comment]
@brandonros _really_ good question! _at present_, no. 
We could _add_ that functionality _relatively_ easily though.

**Comment by brandonros** [comment]
@nelsonic I'm trying to think why it blocks the event loop and takes 8s+ to decache a few files?

**Comment by nelsonic** [comment]
@brandonros the blocking is due to [`find.fileSync'](https://github.com/dwyl/decache/blob/499f6e0689a682a213474099b94cb308d788f30c/decache.js#L37) does your project have a _lot_ of files...? (_we've never seen `decache` take more than a few milliseconds..._) :confused:

**Comment by brandonros** [comment]
What is your definition of a lot?

**Comment by nelsonic** [comment]
@brandonros please try the latest version of `decache` and tell us if you still have issues. it's _Asynchronous_ now. 😉

**Comment by brandonros** [comment]
I rolled my own.

```
utilities.uncached_require = function (filePath) {
	delete require.cache[require.resolve(filePath)];

	return require(filePath);
};

process.on('SIGUSR2', function () {
	integrations['foo'] = utilities.uncached_require('../integrations/foo.js');

	console.log(new Date(), 'Hot reloaded!');
});
```

Do you see anything wrong with that?

**Comment by nelsonic** [comment]
@brandonros _looks good_, `SIGUSR2` is OS-dependent, guessing you're running Linux _everywhere_?
