### ISSUE TITLE
unable to use with jest

### ISSUE THREAD

**Issue by adambene** [dwyl/decache#27]
Code:
```
const decache = require('decache');
const fs = require('fs');

decache('fs');

```

Command: `jest xxx/__tests__/index.js`

Output:
```
    Test suite failed to run

    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
      
      at Object.<anonymous>.require.decache (node_modules/decache/decache.js:40:12)
      at Object.<anonymous> (xxx/__tests__/index.js:4:1)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

With `node xxx/__tests__/index.js` it works fine.

**Comment by adambene** [comment]
any ideas?

**Comment by anthonygarvan** [comment]
@adambene Jest modifies the `require` module to use it's own caching system I believe. I hit my head against this for a while before I found that jest has it's own way to achieve the same thing - `jest.resetModules()`. After hours of struggles that worked for me the first time. I guess you could add support to decache for this by checking for the jest global and calling reset modules, but it's probably best just to do this the "jest" way.

**Comment by adambene** [comment]
Ah, okay. Thanks for pointing that out.

By the way I restructured our packages to be more testable.

**Comment by dennisat** [comment]
Exclude the node_modules from the bundle.

**Comment by thedewpoint** [comment]
@anthonygarvan you da man
