### ISSUE TITLE
Not decaching children of modules

### ISSUE THREAD

**Issue by cutejs** [dwyl/decache#33]
For some reason I can't get it to remove the children of a module. It just removes the top level module, leaving all children in place. Specifically, I have a module mymodule/index.js and a helper file mymodule/helper.js, index requires helper, but when I decache, the helper and all the node_modules remain in the cache.

Here is an example https://github.com/cutejs/decache-example

Am I doing something wrong?

**Comment by nelsonic** [comment]
@cutejs _thank you_ for opening this issue to ask this question! 
This is exactly what we are testing for in: 
https://github.com/dwyl/decache/blob/6504808289d01bfb3f062e7e9e200b8446f57175/test/test.js#L45

Perhaps we need to make our tests clearer... 🤔

**Comment by cutejs** [comment]
I've found that it's the check
`if (child.parent === mod) {`
which it says is there to prevent infinite recursion, seems to prevent any recursion.

Removing the check caused mymodule to be removed completely. In your test, runcount is not in the child module, so removing only the top level one is sufficient to reset runcount.

What's the case where there might even be infinite recursion? It seems to me eventually you'd just hit the bottom of the tree.

**Comment by nelsonic** [comment]
@cutejs please try `decache@4.3.0` on NPM. thanks. ♻️ 
credit to @jupiter if/when it _works_ ... 👍

**Comment by cutejs** [comment]
Yes that fixes it, child modules are successfully removed 😄

**Comment by nelsonic** [comment]
@cutejs thanks for _confirming_! ✅ 
thanks to @ksuszka & @jupiter for resolving. 👍
