### ISSUE TITLE
require('decache') returns empty object

### ISSUE THREAD

**Issue by dkent600** [dwyl/decache#39]
I'm calling `var decache = require('decache');` as described in the readme, but decache is returned as an empty object, not a function.

**Comment by nelsonic** [comment]
@dkent600 please give (_a lot_) more detail so that we can help understand the issue.

**Comment by dkent600** [comment]
Thanks for your response  :-)

I deleted the node_modules folder, reinstalled, and all is good now.  Sorry for the bother.
