### ISSUE TITLE
How to properly import & use with TypeScript?

### ISSUE THREAD

**Issue by Favna** [dwyl/decache#41]
I'm honestly stumped as to how to properly import and use this library when using TypeScript. That is at least to assume it supports a process started through `ts-node` rather than `node`.

I've tried:

### 1:
```ts
import * as decache from 'decache'

...

decache(path.join(__dirname, '../data/databases/eshop.json'));
```

Which throws this in the compiler:
```
Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("e:/UserFiles/DevProjects/ribbon/node_modules/decache/decache")' has no compatible call signatures.
```

### 2: 

```ts
import decache from 'decache';

...

decache(path.join(__dirname, '../data/databases/eshop.json'));
```

Which fails on runtime throwing:

```
/mnt/e/UserFiles/DevProjects/ribbon/src/components/events.ts:707
      decache(path.join(__dirname, '../data/dex/formats.json'));
      ^
TypeError: decache_1.decache is not a function
    at FSWatcher.fs.watch (/mnt/e/UserFiles/DevProjects/ribbon/src/components/events.ts:707:7)
    at FSWatcher.emit (events.js:182:13)
    at FSWatcher.EventEmitter.emit (domain.js:441:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
error Command failed with exit code 1.
```

### and lastly 3:

```ts
import { decache } from 'decache';

...

decache(path.join(__dirname, '../data/databases/eshop.json'));
```

Which throws the following message in the compiler:

```
Module '"e:/UserFiles/DevProjects/ribbon/node_modules/decache/decache"' has no exported member 'decache'.
```

**Comment by Favna** [comment]
The question will remain however I would like to add that I've taken the code base from the library and ported it straight to a TypeScript file of my own, [see here](https://github.com/Favna/Ribbon/blob/WIP/TypeScript-Port/src/components/decache.ts), that I can use in my project.

I'm 99% sure it works as there are no errors and it continues to the code below the decache however I can only say with 100% certainty when I get to making my TypeScript port of the code I originally required decache for.

Should-be-future implementation of the TypeScript version I wrote (as well as what I currently have working on a regular JS base):

```ts
fs.watch(path.join(__dirname, '../data/dex/formats.json'), (eventType, filename) => {
    if (filename) {
        decache(path.join(__dirname, '../data/dex/formats.json'));
        client.registry.resolveCommand('pokemon:dex').reload();
    }
});
```

**Comment by mathe42** [comment]
#45 fix that...

**Comment by nelsonic** [comment]
`decache@4.5.1` published on NPM with @mathe42's addition. 🚀 
If anyone else still has issues with Typscript please re-open this issue and share the _specific_ error you are seeing.
Thanks! ✨

**Comment by Favna** [comment]
Didn't have time to reply earlier but to be frank the real fix was probably including the Typescript compiler flag `--esModuleInterop`. 

Regardless, thanks for addressing it in the lib guys.
