### ISSUE TITLE
Object.keys(module.constructor._pathCache) __pathCache maybe is undefined

### ISSUE THREAD

**Issue by tianyingchun** [dwyl/decache#46]
Object.keys(module.constructor._pathCache)  is undefined if module.exports = {}l;

**Comment by nelsonic** [comment]
This issue is a bit cryptic. Could you please add some context or use-case so that we can understand what problem you are facing?

**Comment by nelsonic** [comment]
Having `module.exports = {}` (_exporting an **empty** `Object`_) is a unlikely edge case.
But if anyone wants to add the test case, we are happy to accept a Pull Request referencing this issue.
Otherwise closing.
