### ISSUE TITLE
If a module is not cached, when finding the module decache should return false.

### ISSUE THREAD

**Issue by benjaminlees** [dwyl/decache#6]

**Comment by besarthoxhaj** [comment]
Pull request: https://github.com/dwyl/decache/pull/7 

Now it returns undefined, which is more sensible in my point of view. If that is not ok let me know and open the issue again.

**Comment by nelsonic** [comment]
Thanks for fixing that @besarthoxhaj 
@benjaminlees FYI: its good practice to describe the issue in more detail in the issue description (i.e. not just the issue title...)
Thanks guys! :+1:
