### ISSUE TITLE
Cannot re-acquire the module upon decaching.

### ISSUE THREAD

**Issue by p0ut** [dwyl/decache#67]
Hi!

I am currently writing a Discord bot which utilises a module's function inside an event for messages.

```js
autoUpdate()
let command = require('./src/commands/command.js')

client.on('messageCreate', async message => { command.interpreter(message) }
```

Now, I have the following function running at the top to check to see if there has been changes in the files in the 'commands' directory.

```js

function autoUpdate() {
	require("fs").watch(`./src/commands/`, (type, filename) => {
		
		if (!fsTimeout) {
			switch(filename) {
				case "command.js":
					decache('./src/commands/command.js')
					command = require('./src/commands/command.js')
					break;
			}

			fsTimeout = setTimeout(function() { fsTimeout=null }, 5000)
		}
	})
}
```
Now, I keep getting 'command.interpreter is not a function' upon decaching the module, despite setting the require again for the module. Any help?

**Comment by nelsonic** [comment]
Please expand the code example if you can. 
Decaching the module (command) in the body of the function should be avoided. 💭

**Comment by p0ut** [comment]
@nelsonic thanks for the reply! managed to figure it out in the end, it seems as though the 'fstimeout' variable I had created to stop fs.watch from firing 2 events was causing the problems in the end. How strange! 

Anyway, I appreciate you popping a reply, genuinely was stuck on this for a couple of days!

**Comment by nelsonic** [comment]
@p0ut glad you figured it out. Always happy to help. Good luck with your project. 👌
