### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by jfairley** [dwyl/decache#8]
I tried using `decache` in a `beforeEach` block, but it was running so slowly that it was sporadically failing my tests due to exceeding the 2000 ms limit. I ended up switching to a manual delete.

Command that was slow:

```javascript
let hrstart = process.hrtime();
decache('./recordMediaInfoService');
let hrend = process.hrtime(hrstart);
console.log('time: %ds %dms', hrend[0], hrend[1] / 1000000);
```
```
time: 1s 773.199276ms
```

Command that is fast:

```javascript
let hrstart = process.hrtime();
delete require.cache[require.resolve('./recordMediaInfoService')];
let hrend = process.hrtime(hrstart);
console.log('time: %ds %dms', hrend[0], hrend[1] / 1000000);
```
```
time: 0s 0.32261ms
```

**Comment by jfairley** [comment]
I like your library for its simplicity. Hopefully, you can track down the issue. :grinning:

**Comment by nelsonic** [comment]
Hi @jfairley thanks for informing us you are seeing a performance issue.
Can you give us more detail? e.g what system you are running on?
Is your test available on GitHub so we can try to replicate?

**Comment by nelsonic** [comment]
On *initial inspection* the *reason* why `decache` is slower than your "direct" `delete` is that you are is because `decache` is *searching* for the file in your working directory before attempting to delete it from the `require.cache`. 

If you are happy with the manual method and don't have to support windows users, stick with it. :+1: 

However if you want to support windows and have you may need to consider increasing your test timeout limit.
From the fact that you're using a `beforeEach` I'm guessing you are using `mocha` as your testing tool. You could run: `mocha --timeout 15000` to get around this.

**Comment by jfairley** [comment]
Ah... Damned Windows... :trollface:  Luckily, no, I don't have to support Windows users. Only OSX and Linux here.

My code is closed source, so I can't link you to it. I'm running mocha tests with Node 0.10. I haven't tried the same thing in 0.12 or 4.0. My library isn't very large (~700 sloc). I would guess that a search would be that slow if it were also crawling through `node_modules`. Would it be possible to exclude `node_modules` based on the fact that the path starts with `"./"`?

I'm curious about the limitation in Windows. Which part doesn't work? Maybe `require.resolve`?

**Comment by jfairley** [comment]
Or... if it's a windows-specific issue, you could check [`os.type()`](https://nodejs.org/api/os.html#os_os_type) or [`os.platform()`](https://nodejs.org/api/os.html#os_os_platform).

**Comment by nelsonic** [comment]
Good suggestion. we could try that *however* we would need to set up http://www.appveyor.com/ for this project in order to Build/CI on Windows.

**Comment by nelsonic** [comment]
@jfairley guessing you managed to get it working? We have not been able to replicate the slowness. 
however we use tape as our test runner which does not have a `beforeEach` method...
how *many* tests were you running?

**Comment by edwardcodes** [comment]
@jfairley guessing you have figured this out...? 
if you are still having issues please re-open this issue or add more detail.

**Comment by jfairley** [comment]
Sorry for the silence. My "faster" option referenced in the description got the job done, and I haven't been active on that project for a few months. If I run across another need to delete cache, I'll try `decache` again, and let you know how it goes. Until then, :beers:.
