### ISSUE TITLE
decache with glob

### ISSUE THREAD

**Issue by safareli** [dwyl/decache#9]
it will be nice to add option to decache with glob like this
```
var minimatch = require("minimatch")
var decacheWithGlob =  function(glob){
  Object.keys(Module._cache).forEach((filePath) => {
    if(minimatch(path.relative(process.cwd(),filePath),glob)){
      console.log('deleted:'+filePath);
      delete Module._cache[filePath]
    }
  })
}
```

**Comment by nelsonic** [comment]
Agreed, that *would* be nice. Do you want to PR it?

**Comment by safareli** [comment]
is name `decacheWithGlob` ok?

btw on my project it takes about 50ms because there are too many files in cache and also minimatch is doing regex match.

i'll PR it :3

**Comment by nelsonic** [comment]
Yeah, in bigger projects searching through many files can take a while... How do you plan to test the PR?
(if you need help, let us know!)

**Comment by safareli** [comment]
i'm thinking of this:

- convert [glob to regex](https://www.npmjs.com/package/glob-to-regexp)
- [generate random](https://www.npmjs.com/package/randexp) file paths matching that regex
- also generate some other paths that don't match that regex.
- put those paths in require.cache like this `require.cache[path] = true` (we wouldn't actually require thous)
- call `decacheWithGlob` and then check if there are left any paths matching glob and if other ones are still there
- then delete all random paths from cache to not cause problems to other tests

**Comment by edwardcodes** [comment]
At the moment our use-case for this module is very basic. 
adding a `regex` to is unlikely to make it run *faster*... 
If more people request this use-case we can re-open this issue.

**Comment by kenberkeley** [comment]
+1
Using https://github.com/sindresorhus/clear-module for now
